// For manage focus references in FocusManager
export const FOCUS_ID = {
	FORMEXAMPLE_CODE: 'FORMEXAMPLE_CODE',
	FORMEXAMPLE_ANIMAL: 'FORMEXAMPLE_ANIMAL',
	FORMEXAMPLE_QUANTITY: 'FORMEXAMPLE_QUANTITY',
	FORMEXAMPLE_USER: 'FORMEXAMPLE_USER',
	FORMEXAMPLE_DATE: 'FORMEXAMPLE_DATE',
	COMBOBOXEXAMPLE: 'COMBOBOXEXAMPLE',
}
