import {FaMoneyBillWave, FaMoneyCheckDollar} from 'react-icons/fa6'
import {
	LuArrowRight,
	LuArrowRightLeft,
	LuBadgePercent,
	LuBoxes,
	LuCalendar,
	LuCalendarCog,
	LuChevronDown,
	LuChevronUp,
	LuChevronsDownUp,
	LuChevronsUpDown,
	LuCircleCheck,
	LuCircleMinus,
	LuCirclePlus,
	LuCircleUserRound,
	LuCircleX,
	LuClipboardList,
	LuClipboardPen,
	LuClock,
	LuCopy,
	LuCopyPlus,
	LuDatabaseZap,
	LuDownload,
	LuEllipsisVertical,
	LuEye,
	LuFastForward,
	LuFile,
	LuFileChartColumnIncreasing,
	LuFileImage,
	LuFilePlus2,
	LuFilter,
	LuFolder,
	LuFolderOpen,
	LuHandCoins,
	LuHouse,
	LuInfo,
	LuLink2,
	LuLink2Off,
	LuLock,
	LuLockOpen,
	LuLogOut,
	LuMailPlus,
	LuMoon,
	LuPaintbrush,
	LuPencilLine,
	LuPercent,
	LuPlay,
	LuReceiptText,
	LuRefreshCcw,
	LuSearch,
	LuShoppingCart,
	LuSquare,
	LuSquareCheck,
	LuSun,
	LuTrash2,
	LuTriangleAlert,
	LuUsersRound,
	LuWarehouse,
	LuWrench,
	LuUpload,
	LuPackage,
} from 'react-icons/lu'
import {RiProductHuntFill} from 'react-icons/ri'

export const Icons = {
	Options: {
		Options: LuEllipsisVertical,
		Delete: LuTrash2,
		Edit: LuPencilLine,
		Clone: LuCopyPlus,
		Show: LuEye,
		Download: LuDownload,
		AttachEmail: LuMailPlus,
		File: LuFile,
		FileAdd: LuFilePlus2,
		FolderOpen: LuFolderOpen,
		Image: LuFileImage,
		Draw: LuPencilLine,
		Info: LuInfo,
		Minus: LuCircleMinus,
		Add: LuCirclePlus,
		Excel: LuFileChartColumnIncreasing,
		Stop: LuSquare,
		Play: LuPlay,
	},
	Searching: {
		Clear: LuPaintbrush,
		Search: LuSearch,
		Filter: LuFilter,
	},
	Pay: {
		Discount: LuBadgePercent,
		MoneyCheck: FaMoneyCheckDollar,
		PayMoney: LuHandCoins,
		MoneyBillWave: FaMoneyBillWave,
		Percentage: LuPercent,
		ReportMoney: LuClipboardPen,
		Taxes: LuReceiptText,
	},
	Misc: {
		Lock: LuLock,
		Unlock: LuLockOpen,
		Link: LuLink2,
		Unlink: LuLink2Off,
		Arrow: LuChevronUp,
		ArrowLong: LuArrowRight,
		Close: LuCircleX,
		Check: LuCircleCheck,
		PlayerPlayFilled: LuPlay,
		PlayerTrackNextFilled: LuFastForward,
		Clock: LuClock,
		NoData: LuDatabaseZap,
		Reload: LuRefreshCcw,
		Warning: LuTriangleAlert,
		People: LuUsersRound,
		Home: LuHouse,
		User: LuCircleUserRound,
		Logout: LuLogOut,
		Clipboard: LuClipboardList,
		Copy: LuCopy,
		Calendar: LuCalendar,
		EditCalendar: LuCalendarCog,
		Cart: LuShoppingCart,
		StackBox: LuBoxes,
		WareHouse: LuWarehouse,
		Transaction: LuArrowRightLeft,
		Product: RiProductHuntFill,
		Wrench: LuWrench,
		Moon: LuMoon,
		Sun: LuSun,
	},
	CHECKBOXTREE: {
		Check: LuSquareCheck,
		Uncheck: LuSquare,
		HalfCheck: LuSquareCheck,
		ExpandClose: LuChevronUp,
		ExpandOpen: LuChevronDown,
		ExpandAll: LuChevronsUpDown,
		CollapseAll: LuChevronsDownUp,
		ParentClose: LuFolder,
		ParentOpen: LuFolderOpen,
		Leaf: LuWarehouse,
	},
	FileManager:{
		LuUpload: LuUpload,
		LuClipboardList: LuClipboardList,
		LuCircleCheck: LuCircleCheck,
		LuReceiptText: LuReceiptText,
		LuFile: LuFile,
		LuCalendar: LuCalendar,
		LuClipboardList: LuClipboardList,
		LuCircleUserRound: LuCircleUserRound,
		LuWarehouse: LuWarehouse,
		LuReceiptText: LuReceiptText,
		LuPackage : LuPackage,
	}
}

export default Icons
